# Taller de introdución a NUMPY

**Nombre:** David Felipe Peña Huertas  
**Codigo:** 20132020018

## 1. Resumen
### ¿Que hace NUMPY?
Numpy es una libreria de python de motivo matematico que se especializa en la parte de manejo de arreglos N-dimensionales, dicha ventaja caracteristica de la libreria permite que el manejo de dichos arreglos simples o multidimensionales se vuelvan bastante tratables en cuanto a la logica de su aplicación.
### ¿Qué usos se le da en el ámbito científico (Aplicaciones)?
Las aplicaciones principales de la libreria de numpy van principalmente al tratamiento de datos, usualmente se trabaja para realizar el tratamiento de datos, principalmente para usos basicos, para *algebra lineal*, adicionalmente para temas avanzados se maneja para *tratamiento de datos*, *procesamiento de señales*, *procesamiento de imagenes*.
### Historia
NUMPY lanzado aproximadamente en el año 2005 por *Travis Oliphant*, donde la biblioteca fue un desarrollo de una version anterior denominada **Numeric** lanzada por Jim Hugunin 
### Describir 3 funciones/operaciones que no se hayan mencionado en la sesión presencial
1. **numpy.invert:** En operaciones de binarios, retorna la forma invertida de dicho numero binario, como ejemplo del numero binario '*1110101*' la operacion retornaria '*0001010*'.
2. **numpy.vstack:** Permite unir verticalmente de arreglos de tamaño N, ejemplo si se tienen los arreglos [1,2,3] y [4,5,6] la operaciones *vstack* entre ellos retornaria [[1,2,3],[4,5,6]] 
3. **numpy.geomspace:** Genera numeros de un punto de inicio a un punto final, de tal forma que los pasos entre estos numeros crecen logaritmicamente, dependiendo si se le pasa el paramero por default o el parametro de determinados pasos   

~~~~{.python}
np.geomspace(1,256,num=9)
array([  1,   2,   4,   8,  16,  32,  64, 128, 256])
~~~~

In [1]:
#Importar librerias
import numpy as np

## Ejercicios
### Ejercicios Rapidos

In [2]:
matrizPrueba = np.array([[34,23,546,788],[12,1099,434,214],[1234,5454,6466,2323],[2332,657,896,53]])
matrizB = np.arange(12).reshape((3,4))
display(matrizPrueba)
display(matrizB)

array([[  34,   23,  546,  788],
       [  12, 1099,  434,  214],
       [1234, 5454, 6466, 2323],
       [2332,  657,  896,   53]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### ¿Cuál es el índice para el elemento 5454?

In [3]:
display(matrizPrueba[2,1])

5454

#### "Rebane" la matriz matrizPrueba de forma que seleccione las filas pares y todas sus columnas

In [4]:
display(matrizPrueba[1::2])

array([[  12, 1099,  434,  214],
       [2332,  657,  896,   53]])

#### Sacar la raíz cuadrada de los valores de la matriz B

In [5]:
display(np.sqrt(matrizB))

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

#### Cree una matriz de 4x4 y haga su transpuesta

In [6]:
matriz=np.arange(16).reshape((4,4))
display("Matriz",matriz)
display("Matriz transpuesta:",matriz.transpose())

'Matriz'

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

'Matriz transpuesta:'

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

### Escriba un programa para crear un arreglo de dimensión 10x4 y extraiga las primeras 3 filas de ese arreglo y guardelas en una variable llamada slice.

In [7]:
matriz=np.arange(40).reshape((10,4))
display(matriz)
slice=matriz[0:4]
display(slice)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Escriba un programa donde declare dos vectores (Arreglos unidimensionales) con valores aleatorios y luego use una función de la libreria para verificar si esos dos vectores son iguales.

In [8]:
array1=np.random.randint(20,size=10)
array2=np.random.randint(20,size=10)
display(np.array_equal(array1,array2))

False

### Cree una matriz de 6x6 cuya diagonal sea [1,2,3,4,5,6] e imprima la matriz

In [9]:
display(np.diag(np.arange(1,7)))

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

### Investigue el método dot de la libreria Numpy y realice una multiplicación de matrices, La primera matriz debe ser de tamaño 5x3 y la otra matriz de 3x2.

In [10]:
#Metodo dot retorna la multiplicacion punto a punto de dos arreglos, en el caso de matrices bidimensionales,
#retorna la multiplicación de dichas matrices.
matrizA=np.random.randint(20,size=15).reshape(5,3)
matrizB=np.random.randint(20,size=6).reshape(3,2)
display("Matriz A",matrizA)
display("Matriz B",matrizB)
display("Multiplicacion de matrices",np.dot(matrizA,matrizB))

'Matriz A'

array([[ 1, 11, 15],
       [17,  4, 19],
       [ 6,  7,  9],
       [ 8,  7, 19],
       [ 3,  6, 11]])

'Matriz B'

array([[19,  7],
       [ 3,  1],
       [ 3, 13]])

'Multiplicacion de matrices'

array([[ 97, 213],
       [392, 370],
       [162, 166],
       [230, 310],
       [108, 170]])